# Generated by Django 2.2.6 on 2019-10-06 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='descripion',
            new_name='description',
        ),
    ]
